listener 1883
allow_anonymous false

auth_plugin /mosquitto/go-auth.so

auth_opt_backends http
auth_opt_cache false
auth_opt_disable_superuser true

auth_opt_http_host app
auth_opt_http_port 8080
auth_opt_http_getuser_uri /api/v1/mqtt/auth
auth_opt_http_aclcheck_uri /api/v1/mqtt/acl
auth_opt_http_with_tls false
auth_opt_http_response_mode status
auth_opt_http_params_mode json

auth_opt_log_level info
auth_opt_log_dest stdout
