spring:
  application:
    name: CHome-BE
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          debug: ${MAIL_SMTP_DEBUG:false}
          timeout: ${MAIL_SMTP_TIMEOUT:5000}
        starttls:
          enable: ${MAIL_STARTTLS_ENABLE:true}

  datasource:
    url: jdbc:h2:mem:chome
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

app:
  base-url: ${APP_BASE_URL:http://localhost:3000}
  email-token:
    secret: ${APP_EMAIL_TOKEN_SECRET}
  jwt:
    secret: ${APP_JWT_SECRET}
    access-expiration-ms: ${APP_JWT_ACCESS_EXPIRATION_MS:1800000}
    refresh-expiration-ms: ${APP_JWT_REFRESH_EXPIRATION_MS:604800000}
